trigger:
  batch: true
  branches:
    include:
      - develop
      - release

stages:
  - stage: Build
    displayName: Build
    variables:
      - group: LFM - Deployment
    jobs:
      - template: build.yml
