trigger:
  batch: true
  branches:
    include:
      - develop
      - release

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: build.yml
        parameters:
          applicationName: "LifeManager"
