parameters:
  - name: applicationName
    type: string

jobs:
  - job: Build
    displayName: "Build the project"

    pool:
      name: Azure Pipelines
      vmImage: "ubuntu-latest"

    variables:
      ? ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}
      : isMain: true
        buildConfiguration: "Release"
        packageVersion: $(Build.BuildNumber).0
      ? ${{ if not(or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))) }}
      : isMain: false
        buildConfiguration: "Release"
        packageVersion: $(Build.BuildNumber).0-preview
      ACR_NAME: lifemanager.azurecr.io
      ACR_SERVICE_PRINCIPAL_ID: <your-managed-identity-principal-id>

    steps:
      - bash: |
          echo 'Build configuration: ${{ variables.buildConfiguration }}'
          echo 'Package version: ${{ variables.packageVersion }}'

      - task: DockerInstaller@0
        inputs:
          dockerVersion: "17.09.0-ce"

      - task: Docker@2
        inputs:
          containerRegistry: "LifeManager - non-prod - container registry"
          command: "login"

      - task: Docker@2
        inputs:
          containerRegistry: "LifeManager - non-prod - container registry"
          repository: "lfm-workstream"
          command: "buildAndPush"
          Dockerfile: "**/Dockerfile"
