jobs:
  - job: Build
    displayName: "Build the project"

    pool:
      name: Azure Pipelines
      vmImage: "ubuntu-latest"

    variables:
      ? ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/master')) }}
      : isMain: true
        buildConfiguration: "Release"
        packageVersion: $(Build.BuildNumber).0
      ? ${{ if not(or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))) }}
      : isMain: false
        buildConfiguration: "Release"
        packageVersion: $(Build.BuildNumber).0-preview
      serviceConnection: "LifeManager - non-prod - container registry"

    steps:
      - bash: |
          echo 'Build configuration: ${{ variables.buildConfiguration }}'
          echo 'Package version: ${{ variables.packageVersion }}'

      - task: Docker@2
        displayName: "Login to ACR"
        inputs:
          command: login
          containerRegistry: ${{ variables.serviceConnection }}
