name: Build and deploy LFM.Authorization

on:
  workflow_dispatch:
    inputs:
      release-dev:
        description: "Release app to D"
        default: false
        type: boolean
  pull_request:
    branches:
      - develop
      - release
  push:
    branches:
      - develop
      - release
  release:
    types: [published]

jobs:
  main:
    name: A test
    uses: ThijmenBrand-LifeManager/LFM.Pipelines/.github/workflows/main.yml@main
    with:
      project-path: LFM.Workstream
      solution-file: LFM.Workstream/LFM.Workstream.sln
      dockerfile-path: |-
        api.Dockerfile
      force-release-dev: ${{ inputs.release-dev || false }}
      app-name: LFM.Workstream
    secrets: inherit