name: Build and deploy LFM.Workstream

on:
  workflow_dispatch:
    inputs:
      publish-package:
        description: "Publish package"
        default: false
        type: boolean
      release:
        description: "Release app"
        default: false
        type: boolean
  pull_request:
    branches:
      - develop
      - release
  push:
    branches:
      - develop
      - release

jobs:
  test:
    if: github.event_name == 'pull_request' && (github.base_ref == 'develop' || github.base_ref == 'release')
    name: Build and test application
    uses: ThijmenBrand-LifeManager/LFM.Pipelines/.github/workflows/build-and-test.yml@main
    with:
      dotnet-version: 8.0.x
      solution-file: LFM.Wotkstream/LFM.Wotkstream.sln
      build-configuration: Release
      app-name: Workstream
    secrets: inherit

  automatic-deploy:
    needs: [test]
    if: inputs.release == false && github.event_name == 'push'
    name: Automatic deploy to Env
    uses: ThijmenBrand-LifeManager/LFM.Pipelines/.github/workflows/build-docker-image.yml@main
    with:
      environment: develop
      project-path: LFM.Workstream
      dockerfile-path: |-
        api.Dockerfile
    secrets: inherit

  manual-deploy:
    if: inputs.release == true
    name: Manual deploy to env
    uses: ThijmenBrand-LifeManager/LFM.Pipelines/.github/workflows/build-docker-image.yml@main
    with:
      environment: develop
      project-path: LFM.Workstream
      dockerfile-path: |-
        api.Dockerfile
    secrets: inherit
